version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: DockerfileLocal
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Monter le dossier local pour le hot reload
      - ./node_modules:/app/node_modules # Prévenir les conflits de node_modules
    env_file:
      - .env