version: '3.8'

services:
  frontend:
    build: .
    container_name: mxbtiming_front
    restart: always
    ports:
      - "3000:80"
    networks:
      - app_network

networks:
  app_network:
    external: true
